### ISSUE TITLE
What's the reason for using phonemes from text labels?

### ISSUE THREAD

**Issue by skol101** [intory89/StyleVC#4]
Is this because, unlike https://github.com/yl4579/StarGANv2-VC/, in loss calculation you don't use ASR?

**Comment by intory89** [comment]
Voice conversion uses two samples to extract the content(linguistic representation) from one sample and to extract prosody(style) features from the other sample. Therefore, text information is not used in voice conversion works(in some works, text information is used as an auxiliary to learn language information)

I did not use the phoneme-related loss in the objective function. In other words, I didn't use text(phoneme) for the input.

**Comment by skol101** [comment]
Probably I'm missing something here. In prepare_dataset.py there's. 
```python
 if a.dataset == "VCTK":
                text = english_cleaners(text.rstrip()) # 'Please call Stella.' -> 'PLEASE CALL STELLA.'
                phoneme = g2p(text)  
                token_sequence = phoneme_to_sequence(phoneme, 'english_cleaners') 
```
But you're saying token sequence isn't used in input?

**Comment by intory89** [comment]
Oh! It is only used to evaluation for WER. We need to get ground-thruths label(text).

**Comment by skol101** [comment]
So, the code that relies on processing text can be safely taken out ?

**Comment by intory89** [comment]
Yes, since we do not use text tokens for training, you can remove them.
